PROGRAM_TITLE = "BREW-IT"
PROGRAM_VERSION = "1.0"

GUI_WINDOWS_BACKCOLOR = "black"
GUI_WINDOWS_FORECOLOR = "white"
GUI_SCREEN_SIZE = "320x220"

API_URL_PROD = 'http://brewit-001-site1.atempurl.com/Robot.asmx?wsdl'
API_URL_TEST = 'http://192.168.2.100:49146/Robot.asmx?wsdl'

DEFAULT_IDLE_DELAY = 1

STATE_IDLE = 0
STATE_STARTING = 1
STATE_PREFERMENTING = 2
STATE_FERMENTING = 3
STATE_CARBONATING = 4
STATE_DISPENSING = 5
STATE_PAUSING = 6
STATE_ENDPAUSE = 7
STATE_STOPPING = 8



